version: '3'

services:
  frontend:
    build: .
    ports:
      - "8090:8080"
    environment:
      - VITE_API_URL=http://app:5000
    networks:
      - academia-network

networks:
  app-network:
    driver: bridge
