version: '3'

services:
  frontend:
    # Imagen del frontend (ajusta según tu configuración)
    image: prometheus_be_frontend:latest
    build: .
    container_name: prometheus-frontend
    ports:
      - "8090:8080"  # Solo el frontend está expuesto públicamente
    environment:
      # El frontend se conecta al backend usando el nombre del servicio
      - VITE_API_URL=http://app:5000
    networks:
      - academia-network
    restart: unless-stopped
      


networks:
  academia-network:
    driver: bridge
    # Opcional: configuración adicional de la red
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16
