version: '3'

services:
  frontend:
    # Imagen del frontend (ajusta según tu configuración)
    image: prometheus_be_frontend:latest
    build: .
    ports:
      - "8090:8080"  # Solo el frontend está expuesto públicamente
    environment:
      # El frontend se conecta al backend usando el nombre del servicio
      - VITE_API_URL=http://app:5000
      # o la variable que uses para configurar la URL del backend
    depends_on:
      - app
    networks:
      - academia-network

networks:
  academia-network:
    driver: bridge
