version: '3'

services:
  frontend:
    build: .
    ports:
      - "8090:8080"
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
