version: '3'

services:
  frontend:
    # Imagen del frontend (ajusta según tu configuración)
    image: prometheus_be_frontend:latest
    build: .
    container_name: prometheus-frontend
    ports:
      - "8090:5000"  # Solo el frontend está expuesto públicamente
    env_file:
      - .env
    networks:
      - academia-network
    restart: unless-stopped

networks:
  academia-network:
    driver: bridge
    # Opcional: configuración adicional de la red
    # ipam:
    #   config:
    #     - subnet: 172.28.0.0/16
