name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/Prometheus_Be
          git pull origin main
          
          # Enfoque más directo para evitar el error ContainerConfig
          
          # Detener y eliminar contenedores específicos
          echo "Stopping and removing containers..."
          docker stop prometheus-frontend || true
          docker rm prometheus-frontend || true
          
          # Verificar y matar cualquier proceso que use el puerto 8090
          PORT_PID=$(lsof -t -i:8090 || echo "")
          if [ ! -z "$PORT_PID" ]; then
            echo "Killing process using port 8090: $PORT_PID"
            kill -9 $PORT_PID
          fi
          
          # Limpiar imágenes huérfanas
          echo "Cleaning up dangling images..."
          docker image prune -f
          
          # Esperar un momento para asegurar que los puertos se liberen
          sleep 5
          
          # Reconstruir la imagen desde cero
          echo "Building fresh image..."
          docker build -t prometheus_be_frontend:latest .
          
          # Iniciar el contenedor con un comando directo en lugar de docker-compose
          echo "Starting container..."
          docker run -d \
            --name prometheus-frontend \
            -p 8090:8090 \
            --network academia-network \
            -e VITE_API_URL=http://app:5000 \
            --restart unless-stopped \
            prometheus_be_frontend:latest
