name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/Prometheus_Be
          git pull origin main
          
          # En lugar de detener todos los contenedores, solo enfocarse en el frontend
          
          # Detener y eliminar solo el contenedor frontend si existe
          FRONTEND_CONTAINER=$(docker ps -a -q --filter name=prometheus_be_frontend)
          if [ ! -z "$FRONTEND_CONTAINER" ]; then
            echo "Stopping and removing frontend container: $FRONTEND_CONTAINER"
            docker stop $FRONTEND_CONTAINER
            docker rm $FRONTEND_CONTAINER
          fi
          
          # Verificar y matar cualquier proceso que use el puerto 8090
          PORT_PID=$(lsof -t -i:8090 || echo "")
          if [ ! -z "$PORT_PID" ]; then
            echo "Killing process using port 8090: $PORT_PID"
            kill -9 $PORT_PID
          fi
          
          # Eliminar contenedores con el mismo nombre (por si acaso)
          EXISTING_CONTAINER=$(docker ps -a -q --filter name=prometheus_app)
          if [ ! -z "$EXISTING_CONTAINER" ]; then
            echo "Removing existing container: $EXISTING_CONTAINER"
            docker rm -f $EXISTING_CONTAINER
          fi
          
          # Limpiar imágenes huérfanas (<none>)
          echo "Cleaning up dangling images..."
          docker image prune -f
          
          # Limpiar solo las imágenes no utilizadas relacionadas con el frontend
          docker image prune -f --filter "label=com.docker.compose.project=prometheus_be_frontend"
          
          # Esperar un momento para asegurar que los puertos se liberen
          sleep 5
          
          # Construir e iniciar solo el servicio frontend
          docker-compose build frontend
          docker-compose up -d frontend
