name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VPS_HOST }}
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /root/Prometheus_Be
          git pull origin main
          
          # Detener todos los contenedores relacionados
          docker-compose down --remove-orphans
          
          # Limpieza más agresiva de contenedores e imágenes
          # Detener todos los contenedores que usan el puerto 8090
          CONTAINER_ID=$(docker ps -q --filter publish=8090)
          if [ ! -z "$CONTAINER_ID" ]; then
            echo "Stopping container using port 8080: $CONTAINER_ID"
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
          fi
          
          # Verificar y matar cualquier proceso que use el puerto 8090
          PORT_PID=$(lsof -t -i:8080 || echo "")
          if [ ! -z "$PORT_PID" ]; then
            echo "Killing process using port 8080: $PORT_PID"
            kill -9 $PORT_PID
          fi
          
          # Eliminar contenedores con el mismo nombre
          EXISTING_CONTAINER=$(docker ps -a -q --filter name=prometheus_app)
          if [ ! -z "$EXISTING_CONTAINER" ]; then
            echo "Removing existing container: $EXISTING_CONTAINER"
            docker rm -f $EXISTING_CONTAINER
          fi
          
          # Limpiar recursos no utilizados
          docker system prune -f
          
          # Esperar un momento para asegurar que los puertos se liberen
          sleep 5
          
          # Iniciar los contenedores
          docker-compose up -d --build
